var says = [
   "<style>.splash-text{ color:cyan;}</style>Credit to 3kh0",
   "<style>.splash-text{ color:cyan;}</style>3kh0 rocks",
   "<style>.splash-text{ color:cyan;}</style>Check out <a href='https://3kh0.github.io' target='_blank'>3kh0.github.io</a> also",
   "<style>.splash-text{ color:red;}</style>give me your vbux",
   "<style>.splash-text{ color:cyan;}</style>3kh0 reference",
   "Zǎoshang hǎo zhōngguó xiànzài wǒ yǒu BING CHILLING",
   "*explosion sfx*",
   "Does anyone even scroll all the way down?",
   "<style>.splash-text{ color:cyan;}</style>3kh0 is awesome",
   "Redbull gives you wiings",
   "If you skid please submit the link in Alternate links!",
   "Tell me to add games up top",
   "<style>.splash-text{ color:#20C20E;}</style>Ж呖N%@ωψ흥",
   "optimized by Opera AI",
   "<a href='https://discord.gg/auxXTY8x8P' target='_blank'>https://discord.gg/auxXTY8x8P</a>",
   "<a href='https://discord.gg/auxXTY8x8P' target='_blank'>https://discord.gg/auxXTY8x8P</a> also",
   "<a href='https://discord.gg/auxXTY8x8P' target='_blank'>https://discord.gg/auxXTY8x8P</a> again?",
   "&#128128;&#128128;&#128128;",
   "Are you a robot?",
   "Think fast chuckle nuts!", 
   "<style>.splash-text{ color:cyan;}</style>Sponsored by 3kh0", 
   "the person who made this website is pretty cool", 
   "when do I get to go home?", 
   "many hours wasted", 
   "shut up ryan",
   "why do i do this?",
  "Launching intercontinental ballistic missile to your exact location",
  "who dis new computer",
  "wenimechainasuma",
  "Microwave your phone for free robux &#128175;",
  "Free Minecraft? Golly Gee!",
  "Curse you, Perry the Platypus!",
  "<i>Doofenshmirtz Evil Incorporated</i>",
  "New Update?!",
  "Sponsored by RAID Shadow Legends",
  "Certified Poggers",
  "what's your Toss The Turtle hi-score?",
  "Toss the Turtle is fun",
  "P.S. You can read btw",
  "For legal reasons, that's a joke!",
  "You got Clash of Clans on your phone?",
  "Did you know you have rights? The constitution says you do!",
  "gotta go x-games mode",
  "Hello. This is Microsoft Refund Department, how can I help you?",
  "Sir, your games were unblocked over 30 days ago, voiding our return policy",
  'Your Honor, my client pleads "oopsie doopsie"',
  '"It is better to poop in the sink, than to sink in the poop"- Master Oogway',
  "Refresh for a new message",
  "Gotta make a move to a town that's right for me",
  "Town to keep me moovin', keep me groovin', with some energy",
  "Won't you take me to Funkytown?",
  "Nice passwords!",
  "Made you look!",
  "<style>.splash-text{ color:yellow;}</style>WARNING: BRAINCELL LOSS IMMINENT",
  "2 + 2 = 5",
  "I'm not a robot",
  "Hello world",
  "if there is a burger king, is the burger queen wendy's?",
  "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
    "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
    "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
  "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
  "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
  "<style>.splash-text{ color:yellow;}</style>If you wish to support me, click a ad every now and then. It helps out a ton!",
  "Noot Noot",
  "<a href='https://github.com/Memelite70/Memelite70.github.io' target='_blank'>Official Github Repository</a>",
  "shimmy shimmy ay shimmy ahh shimmy ahh",
  "1 + 1 = 3",
  "Avocados from Mexico",
  "Me fail english? That's unpossible!",
  "He stomped on his fruit loops and therefore became a cereal killer.",
  "Microwave your hotdogs for 10 minutes on high for free robux!",
  "Ruh roh, Raggy!",
  "What's this do?",
  "Down in Aberqueque",
  "I've a feeling we're not in Kansas anymore",
  "Do your homework kids",
  "Will the real slim shady please stand up?",
  "We're going to have a problem here",
  "<style>.splash-text i{ color:yellow;}</style>I'm not in danger, Skyler. <i>I am</i> the danger",
  "My cats breath smells like cat food",
  "I'm the one who knocks",
  "YOU'RE CRINGE!",
  "1 in a million (minus 4 zeros)",
  "My name is Walter Hartwell White. I live at 308 Negra Aroya Lane, Albuquerque, New Mexico, 87104.",
  "FREE COOKIES!!!",
  "COOKIES FOR YOU!!!",
  "This is a splash text",
  "Now with even more bugs!",

 ];
var games = [
  "Moto X3M",
  "Moto X3M 2",
  "Moto X3M 3",
  "Moto X3M 4",
  "Moto X3M 5",
  "Moto X3M 6",
  "Stickman Hook",
  "Dreadhead Parkour",
  "Doge Miner",
  "Doge Miner 2",
  "Temple of Boom",
  "Justfall.lol",
  "Mineclicker Re-Excavated",
  "Subway Surfers",
  "The Papa's games collection",
  "Swerve",
  "Super Mario 64",
  "Angry Birds",
  "Bad Piggies",
  "The Henry Stickmin Collection",
  "Core Ball",
  "Dante",
  "Geometry Dash",
  "Minecraft 1.5.2",
  "The Backrooms",
  "Idle Breakout",
  "Fruit Ninja",
  "Cannon Basketball 4",
  "Paper io 2",
  "Retro Bowl",
  "OvO",
  "Tiny Fishing",
  "Drive Mad",
  "Bitlife",
  "Ballistic Chickens",
  "Flappy Bird",
  "Awesome Tanks",
  "Awesome Tanks 2",
  "Missiles",
  "Cookie Clicker",
  "Bloons TD 5",
  "Sketchbook 0.4",
  "Among Us Singleplayer",
  "Drift Boss",
  "Drift Hunters",
  "Stack",
  "Snowball io",
  "Slope",
  "Basket Random",
  "Basket Bros",
  "Basketball Stars",
  "Draw the Hill",
  "Duck Life 1",
  "Duck Life 2",
  "Duck Life 3",
  "Duck Life 4",
  "Duck Life 5: Treasure Hunt",
  "Learn to Fly 1",
  "Learn to Fly 2",
  "Learn to Fly 3",
  "Baldi's Basics",
  "Time Shooter 2",
  "Time Shooter 3",
  "Superhot",
  "Funny Shooter 2",
  "Doom 1993",
  "Quake",
  "Pixel Combat 2",
  "Pixel Gun: Survival",
  "1v1.lol",
  "Blockpost",
  "FNaF 1",
  "FNaF 2",
  "FNaF 3",
  "FNaF 4",
  "FNaF Sister Location",
  "FNaF Pizzaria Simulator",
  "FNaF UCN",
  "Cluster Rush",
  "Blumgi Slime",
  "Blumgi Rocket",
  "TABS",
  "Google Baseball",
  "G-Switch 3",
  "FNaW",
  "Granny",
  "Slither.io",
  "Jacksmith",
  "Tomb of the Mask",
  "Rooftop Snipers",
  "Rooftop Snipers 2",
  "Frying Nemo",
  "Monkey Mart",
  "Toss the Turtle",
  "Snow Rider 3D",
  "Recoil",
  "Eggy Car",
  "House of Hazards",
  "Stick War",
  "Stick Merge",
  "Smash Karts",
  "Snail Bob 1",
  "Snail Bob 2",
  "Snail Bob 3",
  "Snail Bob 4",
  "Snail Bob 5",
  "Snail Bob 6",
  "Snail Bob 7",
  "Snail Bob 8",
  "Happy Wheels",
  "Cut the Rope",
  "Tetris",
  "Murder Game",
  "HexGL",
  "CS:GO Clicker",
  "Google Snake",
  "Google Dino",
  "Raft Wars",
  "Raft Wars 2",
  "AI in the Sky",
  "Roblox",
  "Minesweeper",
  "Super Mario Bros",
  "Bloxors",
  "Commando 2",
  "Minecraft Tower Defence",
  "Super Mario 63",
  "Doodle Jump",
  "Plants vs Zombies",
  "Age of War",
  "Interactive Buddy",
  "Portal Flash",
  "Bacon May Die",
  "Rabbit Samurai",
  "Rabbit Samurai 2",
  "Gimme the Airpod",
  "Game Inside a Game",
  "Santy is Home",
  "The Binding of Issac",
  "Achievement Unlocked",
  "Choppy Orc",
  "Edge not Found",
  "Hextris",
  "Sandboxels",
  "Station 141",
  "Temple Run 2",
  "Tunnel Rush",
  "FNF",
  "Stackball",
  "Incredibox",
  "Slow Roads",
  "Big Tower Tiny Square",
  "Bob the Robber 2",
  "Microsoft Edge Surf",
  "Greybox Testing",
  "Madalin Stunt Cars 2",
  "Madalin Stunt Cars 3",
  "Monster Tracks",
  "N-Gon",
  "Noob Steve Parkour",
  "Rocket League",
  "Scrap Metal",
  "Sort the Court",
  "Space Company",
  "Tanuki Sunset",
  "Shell Shockers",
  "YoHoHo.io",
  "Fancy Pants Adventure",
  "10 Minutes 'till Dawn",
  "Amidst the Clouds",
  "Blob Opera",
  "FreezeNova Cars Simulator",
  "Cell Machine",
  "COD Zombies",
  "CraftMine",
  "Crossy Road",
  "CubeField",
  "Deepest Sword",
  "Doomori",
  "Dragon vs Icy Bricks",
  "Earn to Die",
  "Fireboy and Watergirl: Forest Temple",
  "Kitchen Gun Game",
  "Soccer Random",
  "Super Fowlist",
  "Volley Random",
  "Wallsmash",
  "xx142-b2.exe",
];
says.push("Check out&nbsp" + games[Math.floor(Math.random() * games.length)] + ".");
says.push("Also See&nbsp" + games[Math.floor(Math.random() * games.length)] + "!");
says.push("You should play&nbsp" + games[Math.floor(Math.random() * games.length)] + "!");
says.push("Go play some&nbsp" + games[Math.floor(Math.random() * games.length)] + ".");
says.push("Have some fun with&nbsp" + games[Math.floor(Math.random() * games.length)]);
says.push("Play some&nbsp" + games[Math.floor(Math.random() * games.length)] + "!");
says.push("Check out&nbsp" + games[Math.floor(Math.random() * games.length)] + "! It's worth it!");
says.push("Play some&nbsp" + games[Math.floor(Math.random() * games.length)] +"! It's worth it!");
says.push("Check out&nbsp" + games[Math.floor(Math.random() * games.length)] + "!");
says.push("Go play some&nbsp" + games[Math.floor(Math.random() * games.length)] + "!");
function splashText() {
  document.querySelector(".splash-text").innerHTML =
    says[Math.floor(Math.random() * says.length)];
}
fetch("https://ipv6.wtfismyip.com/json")
.then((response) => response.json())
.then((data) => {
  ipAddress = data.YourFuckingIPAddress;
  says.push(`<style>.splash-text{ color:#20C20E;}</style>Your IP is: ${ipAddress}`);
});

//credit to https://railin.vercel.app/ for the o.g code